<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Provider extends Model {
    use HasFactory;
    use SoftDeletes;
    
    protected $table = 'providers'; // The definition of the attributre table will override the auto definition of the table name generated by laravel
    protected $fillable = ['name', 'site', 'uf', 'email'];// The definition of the fillable attribute will allow the table columns to be filled using static methods on tinker or other functions.

}